name: fakestore-backend-drf
services:
  app:
    image: eduardosilvasc/fakestore-backend-drf:latest
    environment:
      - MODE=DEVELOPMENT #  possible values are: DEVELOPMENT, PRODUCTION, MIGRATE
      - SECRET_KEY=xc3ym=v5$1e2wm+1yxc^0b-d4)u6$n-0pq!hk333r4&l(0232e
      - DEBUG=True #  possible values are: True, False
      - PASSAGE_APP_ID=6BNOXynkzsV7vhLEAmPBXgI7
      - PASSAGE_API_KEY=UfNh1XFayg.3vL9fhUtbUdyLWq9l9NZrpQ6AWh4cxun9yUN81eg6bPplf2L9X8lcDgEdjreqm5W
    ports:
      - 8000:8000